### ISSUE TITLE
`rake run` loses prerequisites somehow?

### ISSUE THREAD

**Issue by kejadlen** [seattlerb/zenweb#18]
I'm not sure how this is happening, but when I modify `index.html` during `rake run`, it doesn't update. Dropping into the `run` task shows the task as having no prerequisites: `<Rake::FileTask .site/index.html => []>`.

**Comment by zenspider** [comment]
Can you show me your wirings that involve `index.html`? And what do you mean by "modify"?

**Comment by kejadlen** [comment]
By modify, I mean editing `index.html`. I don't think there are any extra wirings for it, so not exactly sure what you mean?

I did wind up rolling my own Rack app that just runs `rake` with the expected file which seems to work fine though.

**Comment by zenspider** [comment]
I believe that the latest version is "better" about regenerating on demand. I still think there's SOME issues around dependencies if they're deeper but I haven't isolated them quite yet. I'mma close this one tho as I've had a lot better time with the latest version.
